version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: quote_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: quote_system
    volumes:
      - mongodb_data:/data/db
    networks:
      - quote_network

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    container_name: quote_backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      DATABASE_URL: mongodb://admin:password@mongodb:27017/quote_system?authSource=admin
      JWT_SECRET: your_super_secret_jwt_key_here
      PORT: 3001
    depends_on:
      - mongodb
    networks:
      - quote_network
    volumes:
      - ./packages/backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    container_name: quote_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:3001
    depends_on:
      - backend
    networks:
      - quote_network
    volumes:
      - ./packages/frontend:/app
      - /app/node_modules

volumes:
  mongodb_data:

networks:
  quote_network:
    driver: bridge
